# Generated by Django 2.2.4 on 2019-08-03 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created timestamp')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated timestamp')),
                ('redeemed', models.DateTimeField(verbose_name='redeemed timestamp')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_keys', to=settings.AUTH_USER_MODEL)),
                ('parent_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_key', to='key_share_app.Key')),
                ('redeemed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
