# Generated by Django 2.2.4 on 2019-08-03 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('key_share_app', '0002_auto_20190803_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='parent_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_key', to='key_share_app.Key'),
        ),
        migrations.AlterField(
            model_name='key',
            name='redeemed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='redeemed timestamp'),
        ),
        migrations.AlterField(
            model_name='key',
            name='redeemed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_keys', to=settings.AUTH_USER_MODEL),
        ),
    ]
