# Generated by Django 2.2.4 on 2019-08-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_share_app', '0004_key_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='game_info_cover_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_developer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_genres',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_igdb_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_official_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='released timestamp'),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_screenshots',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_similar_games',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_steam_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_storyline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='game_info_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
