# Generated by Django 2.2.4 on 2019-08-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_share_app', '0005_auto_20190805_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='game_info_time_to_beat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
